# Generated by Django 3.2.5 on 2021-07-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('first_name', models.TextField(max_length=50, null=True)),
                ('last_name', models.TextField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('telephone', models.CharField(max_length=25, null=True)),
                ('address_name', models.TextField(max_length=50, null=True)),
                ('address_number', models.SmallIntegerField(null=True)),
                ('address_aclaration', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
    ]
